### PR TITLE
Add #hackage.

### PR DESCRIPTION
**Pull request by 23Skidoo**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
@chrisdone Is there anything I can do to get this merged? I realise that this is more involved than just adding a couple of lines to the import module.

**Comment by chrisdone** [comment]
http://ircbrowse.net/browse/hackage

**Comment by 23Skidoo** [comment]
Great, thanks! Maybe we can also import log archive from https://phabricator.haskell.org/chatlog/channel/4/?

**Comment by chrisdone** [comment]
@23Skidoo if you can get an export log file or files in plain text, preferrably in ZNC format, like [this](http://chrisdone.com/haskell_20130921.txt) then I can import them.

**Comment by 23Skidoo** [comment]
@chrisdone I'll ask @thoughtpolice.

**Pull request merged**
