### PR TITLE
reinstate the #scalaz channel, as agreed in discussion

### PR DESCRIPTION
**Pull request by tonymorris**
https://github.com/scalaz/scalaz/issues/973

### CODE REVIEW

**Comment by greenrd** [comment]
@tonymorris @chrisdone ircbrowse.net has not actually been recording #scalaz since 13 July, it seems. I wonder if the last message recorded (which is probably garbled by the ircbrowse code) is relevant:

2015-07-13 10:32:32 +0200	ircbrowse	dibblegoircbrowse

**Comment by chrisdone** [comment]
I think removing it has confused the import process, but I haven't had time to look into exactly how.

**Comment by chrisdone** [comment]
Okay, there was a missing log file for 2015-07-14 after the vnc was kicked, so the import process did not proceed beyond 2015-05-13. I created a dummy file so that it could proceed. It's working now.

**Comment by chrisdone** [comment]
It'll take a while for the site to update fully via the partial update cronjob. There's a full import process nightly.

**Pull request merged**
