### PR TITLE
Added #reflex-frp

### PR DESCRIPTION
**Pull request by zudov**
I didn't test this, but hopefully I got it right.

### CODE REVIEW

**Comment by jhegedus42** [comment]
How should this be fixed? How can one log reflex-frp ?

**Comment by zudov** [comment]
@jhegedus42 Assuming that my patch is correct it's now up to @chrisdone to deploy the new configuration

**Comment by zudov** [comment]
Great :)

**Comment by chrisdone** [comment]
Deployed!

**Comment by zudov** [comment]
@chrisdone \o/ Thanks

**Comment by jhegedus42** [comment]
Thank you very much Chris !

Jozsef

**Comment by chrisdone** [comment]
:+1:

**Pull request merged**
